config/routes.rb
Broomble::Application.routes.draw do
  devise_for :users

  resources :pages
  resources :links

  root :to => "pages#index"

end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :title, :body, :url

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
 	attr_accessible :email, :username

 	has_many :links
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
	
	respond_to :html, :xml, :js

	def index
		@links = Link.all
	end

	def show
		@link = Link.find(params[:id])

		respond_with @link
	end

	def new
		@link = Link.new
	end

	def create
		# @link = Link.new
		# @link.save

		# flash.notice = "Link has been submitted"
		# redirect_to link_path(@link)

		@link = Link.new(params[:link])

    respond_to do |format|
    	if @link.save
    		format.html { redirect_to @link, notice: 'Story was successfully created.'}
    		format.json { render json: @link, status: :created, location: @link }
    	else
    		format.html { render action: "new"}
    		format.json { render json: @link.errors, status: :unprocessable_entity}
    	end
    end
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Broomble</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%# user is logged in, show log out link %>
<% if current_user.present? %>
	<%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>
<%# user is not logged in, show signup and login links %>
<% else %>
	<%= link_to 'Sign in', new_user_session_path %> | 
	<%= link_to 'Register Now', new_user_registration_path %>
<% end %>

<%= yield %>

</body>
</html>

app/views/links/_form.html.erb
 <%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/index.html.erb
<h1>All Links</h1>

<ul id="links">
<% @links.each do |link| %>
	<li>
		<%= link_to link.title, link_path(link), class: 'link_title' %>
	</li>

	<% end %>
</ul>

app/views/links/new.html.erb
 <%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/show.html.erb
<h1><%= @link.title %></h1>


<p>URL: <%= @link.url %></p>

app/views/pages/index.html.erb
<h2>I AMA Homepage</h2>

<%= link_to "Add a link", new_link_path %>